version: 2.1

workflows:
  my-workflow:
    jobs:
      - run-tests

jobs:
  run-tests:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo something"
          command: echo "something"
